[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings=["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
fs_permissions = [
    { access = "read", path = "./img/" },
    { access = "read", path = "./broadcast" },
]
ffi = true
evm_version = "paris"